### ISSUE TITLE
Error after updating to 22.11

### ISSUE THREAD

**Issue by darrelwright** [eliranwong/UniqueBible#231]
Traceback (most recent call last):
  File "main.py", line 43, in <module>
    from gui.MainWindow import MainWindow
  File "/home/darrel/UniqueBible-master/gui/MainWindow.py", line 22, in <module>
    from gui.EditGuiLanguageFileDialog import EditGuiLanguageFileDialog
  File "/home/darrel/UniqueBible-master/gui/EditGuiLanguageFileDialog.py", line 4, in <module>
    from qtpy.QtCore import QAbstractTableModel, Qt, SIGNAL
ImportError: cannot import name 'SIGNAL' from 'qtpy.QtCore' (/home/darrel/.local/lib/python3.8/site-packages/qtpy/QtCore.py)

**Comment by eliranwong** [comment]
@darrelwright when does it happen?  can you describe what action causes this error?

**Comment by eliranwong** [comment]
can u try to do the same in 22.13 and see if still errors?

**Comment by darrelwright** [comment]
How to install UBA? This error stops it from running.

**Comment by darrelwright** [comment]
Ok, I had to rebuild UBA, but I appear to up and running with 22.13 now

**Comment by eliranwong** [comment]
I think I fixed the signal import issue in 22.14

just uploaded a min ago.  make sure you use the latest one.

Please also note that we changed the way UBA is installed recently.

read https://github.com/eliranwong/UniqueBible/wiki/installation

it should be much easier than before.

@darrelwright

**Comment by eliranwong** [comment]
> Ok, I had to rebuild UBA, but I appear to up and running with 22.13 now

@darrelwright 
did you try our new way to install?

https://github.com/eliranwong/UniqueBible/wiki/installation

**Comment by darrelwright** [comment]
Yes, and I like it!

**Comment by eliranwong** [comment]
@darrelwright shortcut file is automatically created.

also, use uba.py instead of main.py to run UBA
