### ISSUE TITLE
Error after updating to 22.11

### ISSUE THREAD

**Issue by darrelwright** [eliranwong/UniqueBible#230]
Traceback (most recent call last):
  File "main.py", line 43, in <module>
    from gui.MainWindow import MainWindow
  File "/home/darrel/UniqueBible-master/gui/MainWindow.py", line 22, in <module>
    from gui.EditGuiLanguageFileDialog import EditGuiLanguageFileDialog
  File "/home/darrel/UniqueBible-master/gui/EditGuiLanguageFileDialog.py", line 4, in <module>
    from qtpy.QtCore import QAbstractTableModel, Qt, SIGNAL
ImportError: cannot import name 'SIGNAL' from 'qtpy.QtCore' (/home/darrel/.local/lib/python3.8/site-packages/qtpy/QtCore.py)

**Comment by darrelwright** [comment]
duplicate
